# Generated by Django 6.1.1 on 2026-10-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='acompanamiento',
            field=models.CharField(choices=[('ENSALADA', 'Ensalada'), ('CONSOME', 'Consomé'), ('NINGUNO', 'Sin acompañamiento')], default='NINGUNO', max_length=20, verbose_name='Acompañamiento'),
        ),
    ]
