# Generated by Django 6.1.1 on 2026-10-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_itempedido_acompanamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('DELIVERY_EFECTIVO', 'Efectivo al Delivery'), ('DELIVERY_TARJETA', 'Tarjeta al Delivery'), ('DELIVERY_TRANSFERENCIA', 'Transferencia al Delivery'), ('LOCAL_EFECTIVO', 'Efectivo en el Local'), ('LOCAL_TARJETA', 'Tarjeta en el Local'), ('LOCAL_TRANSFERENCIA', 'Transferencia en el Local')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
