# Generated by Django 6.1.1 on 2026-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidos_metodo_pago_pedidos_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='platomenu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/', verbose_name='Imagen del Plato'),
        ),
    ]
