# Generated by Django 6.1.1 on 2026-10-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo_giftcard',
            field=models.IntegerField(default=0, verbose_name='Saldo Gift Card'),
        ),
    ]
