# Generated by Django 6.1.1 on 2026-10-09 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_saldo_giftcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Debe terminar con un guion y un solo número o letra K (Ej: 12.345.678-9).', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[0-9Kk]$')], verbose_name='Rut'),
        ),
    ]
